name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}
api-version: "1.13"
softdepend: [NoCheatPlus]
commands:
  superpickaxe:
    description: Enables or disables superpickaxe.
    usage: /command
    aliases: [spa]
