name: SuperpickaxeReloaded
main: eu.internetpolice.spa.SuperpickaxeReloaded
version: ${project.version}
api-version: "1.13"
softdepend: [NoCheatPlus]
commands:
  superpickaxe:
    description: Enables or disables superpickaxe.
    usage: /command
    aliases: [spa]
